### PR TITLE
PDE-4678 fix(cli): `zapier build` fails with npm workspaces

### LINKED ISSUE #648: [Bug]: zapier push fails with npm workspaces
### Bug Description

Executing `zapier push` fails with an error: 
```
Looks like you're missing a local installation of zapier-platform-core. Run `npm install` to resolve
```

### Reproduction Steps

1. in the package.json at the root of the monorepo, add a folder `/my-adapter` and include it in the list of workspaces (see [npm workspaces](https://docs.npmjs.com/cli/v9/using-npm/workspaces))
2. from the monorepo root, install zapier packages: `npm install zapier-platform-cli zapier-platform-core --workspace my-adapter`
3. implement the code for a zapier adapter in `/my-adapter`
4. `cd ./my-adapter && npm run build && npx zapier push` throws an error complaining about missing local installation

### Zapier Platform version

14.0.0

### Node.js version

18.15.0

### Your Operating System

macos

### npm/yarn version

9.6.3

### App ID

160973

### More Details

_No response_

### PR DESCRIPTION
**Pull request by eliangcs**
Fixes #648.

Some developers may choose to structure their project using [npm workpaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces) or [yarn workspaces](https://classic.yarnpkg.com/lang/en/docs/workspaces/). An example project structure might look like:

```
(project root)
├─ package.json
└── packages/
    ├─ app-1/
    │  ├─ index.js
    │  └─ package.json
    └─ app-2/
        ├─ index.js
        └─ package.json
```

If you run `npm install` in the above example, `app-1` and `app-2` will share their dependencies in the project root's `node_modules`. Only the dependencies with version discrepancies will be placed into `app-1/node_modules` or `app-2/node_modules`.

The current implementation of `zapier build` doesn't support workspaces. It always assume it can always find `zapier-platform-core` in the working directory's `node_modules`.

This PR fixes that by finding `zapier-platform-core` in the working directory _and_ all the parent directories.

### CODE REVIEW

**Comment by eliangcs** [comment]
@rnegron this is still work-in-progress as I'd like to add some test cases. But you might want to take a look first, because I also modified `copyDir()` as you did in #737.

**Comment by rnegron** [comment]
@eliangcs 

> But you might want to take a look first, because I also modified copyDir() as you did in https://github.com/zapier/zapier-platform/pull/737.

Thanks for letting me know! Let's use this PR for those initial `async/await` changes, since I will likely modify it further to add some `fs.lstatSync(...).isSymbolicLink()` related logic!

File: packages/cli/src/utils/files.js [hunk 1]
```diff
@@ -83,60 +83,87 @@ const copyFile = (src, dest, mode) => {
...
 };
 
-// Returns a promise that copies a directory.
-const copyDir = (src, dst, options) => {
-  const defaultFilter = (dir) => {
-    const isntPackage = dir.indexOf('node_modules') === -1;
-    const isntBuild = dir.indexOf('.zip') === -1;
+/*
+  Returns a promise that copies a directory recursively.
+
```
Comment (rnegron) [inline packages/cli/src/utils/files.js:88]: 👍🏻  Always appreciate these descriptive comments

**Review by rnegron — DISMISSED** [review]

File: packages/cli/src/utils/build.js [hunk 2]
```diff
@@ -383,9 +414,7 @@ const _buildFunc = async ({
     path.join(tmpDir, 'zapierwrapper.js'),
     zapierWrapperBuf.toString()
   );
-  endSpinner();
 
-  startSpinner('Building app definition.json');
```
[the remark this answers is not in the document]
Comment (eliangcs) [reply packages/cli/src/utils/build.js:388]: It was a mistake. Added it back in [52fba09](https://github.com/zapier/zapier-platform/commit/52fba09b195add7cd30fa7ed19efeb8775fbf31c). Thanks!

**Comment by eliangcs** [comment]
@rnegron I merged your PR #737 and added some code to exclude workspace symlinks, such as `node_modules/app-1` and `node_modules/app-2`, from the `build.zip`. Can you re-review? Thanks a lot!

File: packages/cli/src/utils/build.js [hunk 3]
```diff
@@ -332,24 +353,69 @@ const _buildFunc = async ({
...
+            return false;
+          }
+          const stat = fse.lstatSync(src);
+          if (stat.isSymbolicLink()) {
+            const realPath = path.resolve(
+              path.dirname(src),
+              fse.readlinkSync(src)
+            );
+            for (const workspace of workspaces) {
+              if (minimatch(realPath, workspace)) {
```
Comment (rnegron) [inline packages/cli/src/utils/build.js:398]: @eliangcs Could we add a comment here explaining what this `minimatch` line is doing? I believe it's `true` if the `src` symlink resolves (points to) to a workspace path, in which case we want to filter out (`return false`) this particular `src`. So that we don't copy over any symlinks that point to workspace folders.

**Review by rnegron — APPROVED** [review]

File: packages/cli/src/utils/build.js (hunk 3 above)
Comment (eliangcs) [reply packages/cli/src/utils/build.js:398]: You interpretation is correct. Since the `workspaces` array in the root `package.json` can contain glob patterns, like `packages/*`, I use minimatch to help us do glob pattern matching. I'll add a comment in a separate PR. Thanks!
